### ISSUE TITLE
bulma-toast not supporting IE11

### ISSUE THREAD

**Issue by JeannePk** [rfoel/bulma-toast#17]
I have an angular project with bulma-toast configured.
When I try to start the project with `ng serve` in Internet Explorer 11, I have the following errors in the console:

```
SCRIPT1014: Invalid character
vendor.js (122891,459)
```

Which refer to the following:
![screenshot](https://image.noelshack.com/fichiers/2019/06/4/1549544558-capture2.jpg)

Does bulma-toast support IE?

Versions;
"bulma": "^0.7.2",
"bulma-toast": "^1.4.0"
Internet Explorer v11.523.17134.0

**Comment by CleyFaye** [comment]
Hi,

I've faced the same issue. IE11 does not understand much of the "recent" JavaScript features like arrow functions.
Since I don't think cramming IE11 compatibility in newer code is a good idea, I made a fork that just use babel to generate ES5/IE11 compatible files:
https://github.com/KeeeX/bulma-toast

I try to keep it up to date with this repo, but it's not a big priority. If you prefer you can just clone this repos, add babel in the build config and use that.
Main changes are:

- adding babel dependencies
- adding config in .babelrc
- adding babel plugin in the rollup config.

Note: it might be possible to do this using only the already present babel-minify plugin, but as I said this was low priority for me, I just needed something quick :)

**Comment by rfoel** [comment]
Fell free to make a pull request with your changes if you want. I guess I could do it with some rollup config but I haven't had much time either.

**Comment by CleyFaye** [comment]
I'm not sure it'd be a good idea. Either you'd need to always make IE11-friendly versions, which mean losing some feature and including a lot of polyfills, or make an IE11-friendly version with a different name in the dist directory.

If I get around making this second option at some point I'll make a PR (it would be cleaner than what I actually did).
